modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="lemon_core"
version="1.20.1-1.0.19"
displayName="Lemon Core"
logoFile="lemon_core.png"
authors="Lemon_Juiced & Scalar Team"

description='''
A set of core items and tagged materials for use in my other mods and cross-play.
'''

[[dependencies.lemon_core]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lemon_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
