modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="lemon_core"
version="1.19.4-1.0.5"
displayName="Lemon Core"
logoFile="lemon_core.png"
credits="Lemon_Juiced"
authors="Lemon_Juiced"

description='''
A set of core items and tagged materials for use in my other mods and cross-play.
'''

[[dependencies.lemon_core]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lemon_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
